export const cuisineTypeEnum = Object.freeze({
    AMERICAN: 'AMERICAN',
    MEXICAN: 'MEXICAN',
    ITALIAN: 'ITALIAN',
    FRENCH: 'FRENCH',
    GREEK: 'GREEK',
    DUTCH: 'DUTCH',
    POLISH: 'POLISH',
    HUNGARIAN: 'HUNGARIAN',
    INDIAN: 'INDIAN',
    CHINESE: 'CHINESE',
    JAPANESE: 'JAPANESE',
    KOREAN: 'KOREAN',
    VIETNAMESE: 'VIETNAMESE',
    THAI: 'THAI',
    MONGOLIAN: 'MONGOLIAN',
    OTHER: 'OTHER'
});
